#!/usr/bin/env php
<?php
$doc = <<<DOC
Generate diff

Usage:
  gendiff (-h|--help)
  gendiff (-v|--version)
  gendiff [--format <fmt>] <firstFile> <secondFile>
  
Options:
  -h --help                     Show this screen
  -v --version                  Show version
  -- format <fmt>               Report format [default: stylish]
DOC;

require_once ('vendor/docopt/docopt/src/docopt.php');
Docopt::handle($doc, array('version' => 'gendiff 1.0'));